name: Upload process to server

on:
  workflow_dispatch:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu 

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: List all files in the repository
        run: |
          echo "Looking for .json files..."
          find . -name "*.json" -type f | while read file; do
            echo "Processing $file..."
            upload-generic-process admin admin https://10.134.119.177:8443 "$file"
          done
