name: Upload process to server

on:
  workflow_dispatch:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu 

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -al  # Shows all files including hidden ones
